version: "3.8"
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./front.tf:/var/jenkins_home/front.tf
    privileged: true
    environment:
      - JENKINS_URL=http://localhost:8080/
volumes:
  jenkins_home: