version: "3.8"
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/upao/.ssh/id_rsa:/home/upao/.ssh/id_rsa:ro
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    privileged: true
    environment:
      - JENKINS_URL=http://localhost:8080/
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - DOCKER_HOST=tcp://docker-agent:2375
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    networks:
      - dev-net
    group_add:
      - 103

  docker-agent:
      image: docker:24.0.7-dind
      container_name: docker-agent
      privileged : true
      networks:
        - dev-net
      ports:
        - "2375:2375"
      command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--tls=false"]
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - dev-net

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - ./Promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - ./logs:/var/log/app
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - dev-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/datasources
    networks:
      - dev-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
 
volumes:
  jenkins_home:
  grafana-storage:
networks:
  dev-net: